version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-buster
    steps:
      - checkout
      - run:
          name: Get Pull Request Body
          command: |
            # Get Pull Request Number
            LOG=`git log --first-parent origin/master -1 --pretty="%s (%an)"`
            PR_NUMBER=`echo "$LOG" | sed -e 's/Merge pull request #\([0-9]*\) .*$/\1/g'`
            echo "export PR_NUMBER=$PR_NUMBER" >> $BASH_ENV
            source $BASH_ENV

            # Get Pull Request Body
            gem install octokit
            PR_BODY=`ruby ./.circleci/get_pull_request.rb`
            echo $PR_BODY
            echo "export PR_BODY=$PR_BODY" >> $BASH_ENV
            source $BASH_ENV
      - slack/status:
          channel: 'dev-dojo'
          success_message: "<!here>\n*TEST*\n$PR_BODY"
workflows:
  build_and_push_image:
    jobs:
      - build
#      - aws-ecr/build-and-push-image:
#          create-repo: true
#          dockerfile: Dockerfile
#          repo: my-ruby
#          tag: 'latest,$CIRCLE_SHA1'
