version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-buster
    steps:
      - run:
          name: Set environment
          command: |
            echo "export MESSAGE=\"TESTですYO\n#2288 hogehoge\n#2289 fugafuga\n\"" >> $BASH_ENV
            source $BASH_ENV
            echo $MESSAGE
      - slack/status:
          mentions: 'here'
          success_message: $MESSAGE
workflows:
  build_and_push_image:
    jobs:
      - build
#      - aws-ecr/build-and-push-image:
#          create-repo: true
#          dockerfile: Dockerfile
#          repo: my-ruby
#          tag: 'latest,$CIRCLE_SHA1'
